export const ADVERTS_REQUEST = 'ADVERTS_REQUEST';
export const ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILURE';
export const ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const TAGS_REQUEST = 'TAGS_REQUEST';
export const TAGS_FAILURE = 'FETCH_TAGS_FAILURE';
export const TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const SAVE_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';
