export const API_REQUEST = 'API_REQUEST';
export const API_FAILURE = 'API_FAILURE';
export const GO_LOGIN = 'GO_LOGIN';
export const GO_REGISTER = 'GO_REGISTER';
export const GO_USER_REGISTERED = 'GO_USER_REGISTERED';
export const GO_APP = 'GO_APP';
// export const GO_DETAIL = 'GO_DETAIL';


// export const GOHOME_SUCCESS = 'GOHOME_SUCCESS';


export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_INVALID = 'REGISTER_INVALID';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_INVALID = 'LOGIN_INVALID';




export const ADVERTS_SUCCESS = 'ADVERTS_SUCCESS';
export const ONE_ADVERT_SUCCESS = 'ONE_ADVERT_SUCCESS';
export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';

export const DIVIDE_IN_PAGES = 'DIVIDE_IN_PAGES';
export const PAGE_BACK = 'PAGE_BACK';
export const PAGE_FORWARD = 'PAGE_FORWARD';

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

